FROM openjdk:13-ea-19-jdk-alpine3.9
RUN apk update
RUN apk upgrade 
RUN apk add bash 
RUN apk add curl
RUN apk add wget
RUN apk add git 
RUN apk add vim 
RUN apk add unzip 
RUN apk add screen 

COPY vimrc /root/.vimrc
COPY bashrc-java /root/.bashrc

