FROM debian:stretch-slim

ENV SHELL /bin/bash

RUN echo "deb http://deb.debian.org/debian/ stable main contrib non-free" >> /etc/apt/sources.list
RUN echo "deb-src http://deb.debian.org/debian/ stable main contrib non-free"
RUN echo "deb http://deb.debian.org/debian/ stable-updates main contrib non-free"
RUN echo "deb-src http://deb.debian.org/debian/ stable-updates main contrib non-free"
RUN echo "deb http://deb.debian.org/debian-security stable/updates main"
RUN echo "deb-src http://deb.debian.org/debian-security stable/updates main"
RUN echo "deb http://ftp.debian.org/debian stretch-backports main"
RUN echo "deb-src http://ftp.debian.org/debian stretch-backports main"

RUN echo 'Package: * \nPin: release a=stretch-backports \nPin-Priority: 1000 \n' >> /etc/apt/preferences.d/00-backports

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y gcc g++  
RUN apt-get install bash -y
RUN apt-get install curl -y
RUN apt-get install wget -y
RUN apt-get install git -y
RUN apt-get install vim -y
RUN apt-get install unzip -y
RUN apt-get install screen -y
RUN apt-get install python -y
RUN apt-get install python-pip -y

RUN pip install troposphere
RUN pip install awacs
RUN pip install argparse
RUN pip install awscli
WORKDIR /root
RUN wget https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip
RUN unzip packer_1.4.1_linux_amd64.zip

RUN apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common \
  lsb-release \
    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | apt-key add - 2>/dev/null \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
    && apt-get update

RUN apt-get -y install docker-ce-cli

RUN pip install git+https://github.com/pdex/aptly_api_cli.git@0.3

COPY vimrc /root/.vimrc
COPY bashrc-debian /root/.bashrc

