FROM rust:1.34-stretch

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install bash -y
RUN apt-get install curl -y
RUN apt-get install wget -y
RUN apt-get install git -y
RUN apt-get install vim -y
RUN apt-get install unzip -y
RUN apt-get install screen -y

COPY vimrc /root/.vimrc
COPY bashrc-rust /root/.bashrc
