FROM node:12.2.0-alpine
RUN apk update
RUN apk upgrade
RUN apk add bash
RUN apk add curl
RUN apk add wget
RUN apk add git
RUN apk add vim
RUN apk add openssh
RUN apk add unzip
RUN apk add screen
RUN npm install -g skygragon/leetcode-cli
COPY vimrc /root/.vimrc
COPY bashrc-leetcode /root/.bashrc


